### ISSUE TITLE
Error when writing MbsLists using MbsDynamicHelper?

### ISSUE THREAD

**Issue by Monkeytron** [Stencyl/haxe-mbs#1]
If anyone who understands this code more than me sees this, can you help me please?

Basically MbsObject has a method "getMbsType()" which should be overridden in derived classes. However, it does not seem to be overridden in MbsListBase or any classes derived from that - and therefore, if attempting to write any Mbs List using MbsDynamicHelper.WriteDynamic(), which calls getType() to write the typecode, it will throw an error.

How do I fix this / is there something I'm missing?

(An example of this situation would be when writing MbsAttribute s from stencyl-engine: they have a field "value" which is a dynamic, and can sometimes be an MbsDynamicList.

**Comment by justin-espedal** [comment]
It looks like a simple oversight. There's a Java version of this code, for use by the toolset. For Stencyl's purposes, that's where all mbs writing happens. The Haxe side is mostly the same, but since it was never intended for use writing mbs files, any writing code on the Haxe side was never tested.

I've pushed a commit that should fix this issue, but perhaps you'll find others. ae018c54924f4a2bc86776acf443c24c7b1e4901

**Comment by Monkeytron** [comment]
Is the java version available and open source? I'm currently struggling to get this code to work, and it would be helpful if I could see the code stencyl actually uses to see if there are any issues.

Also, has the reading code from this and stencyl-engine been tested, or is that only an example too?

**Comment by justin-espedal** [comment]
It's not available right now, no. But the Java version of this code is pretty much a 1:1 port of the Haxe code so it wouldn't really help.

Being able to see the source of the Stencyl toolset would help much more, since it has examples of the writing code, but there are no plans to open source that right now either.

Yes, the engine does use the mbs readers to read game data. `Data.hx` initially reads the mbs data into memory, and then passes the data off to individual readers (the classes in the `com.stencyl.io` package, as well as `com.stencyl.models.Scene` and `com.stencyl.models.GameModel`).

A basic overview of writing an mbs file (using MbsGame as an example) without getting into the specifics looks like this:
```haxe
import com.stencyl.io.mbs.game.MbsGame;
import com.stencyl.io.mbs.Typedefs;
import mbs.io.*;
...

MbsWriter writer = new MbsWriter(Typedefs.get(), false);
MbsGame game = new MbsGame(writer);
game.allocateNew();
writer.setRoot(game);
//write data to the mbs game
//...
writer.prepareForOutput();
writer.writeToFile(file);
```

the `//write data to the mbs game` portion needs to be replaced with all of the type-specific data setters. For that, you can look at how the type you're interested in is read in the engine (using the files I mentioned above) and reversing that.

---

What are you trying to do? It might not make sense to write a large amount of mbs read/write code when mbs itself could likely be modified to more easily achieve what you're attempting.

**Comment by Monkeytron** [comment]
I was really just seeing if I could translate the mbs read/write code into c# (as I am more familiar with that language), as an experiment.

Thank you for that fix, my version now seems to work so I think the remainder of the code here is correct / bug free.
